include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false

analyzer:
  exclude:
    - lib/generated/**
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/**.auto_mappr.dart
