name: Common Setup
description: "Sets up Java and Flutter for reusability"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        distribution: "zulu"
        java-version: "21"
        cache: gradle

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.38.x"
        channel: "stable"
        cache: true

    - name: Activate Melos
      shell: bash
      run: dart pub global activate melos

    - name: melos bootstrap
      shell: bash
      run: melos bootstrap

    - name: melos rebuild:all
      shell: bash
      run: melos rebuild:all

    - name: melos bootstrap
      shell: bash
      run: melos bootstrap
