name: Version
description: Create version number
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: "5.x"

    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.10.2

    - name: Create version.txt with nuGetVersion
      shell: bash
      run: echo ${{ steps.gitversion.outputs.nuGetVersion  }} > version.txt

    - name: Upload version.txt
      uses: actions/upload-artifact@v4
      with:
        name: gitversion
        path: version.txt
