name: multichoice
description: "The application for the Multichoice repo"
publish_to: "none"

version: 0.1.0+103

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.3
  core: ^0.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_hooks: ^0.20.5
  gap: ^3.0.1
  models: ^0.0.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
