name: multichoice
description: "The application for the Multichoice repo"
publish_to: "none"

version: 0.3.0+152

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  auto_route: ^10.0.1
  bloc: ^9.0.0
  core: ^0.0.1
  file_picker: ^9.0.2
  firebase_core: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_hooks: ^0.21.2
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  gap: ^3.0.1
  models: ^0.0.1
  permission_handler: ^11.3.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  theme: ^0.0.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.5.0+1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true
  output: lib/generated/
