name: multichoice
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.2+88

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  bloc: ^8.1.3
  core: ^0.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  gap: ^3.0.1
  models: ^0.0.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
