name: multichoice
description: "The application for the Multichoice repo"
publish_to: "none"

version: 0.4.0+132

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  auto_route: ^8.1.3
  bloc: ^8.1.3
  core: ^0.0.1
  firebase_core: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_hooks: ^0.20.5
  gap: ^3.0.1
  models: ^0.0.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  theme: ^0.0.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
