---
version: 2
updates:
  #---------------------------
  # Github Actions
  #---------------------------
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      # day: "sunday"
      time: "06:00"
    target-branch: "develop"
    labels:
      - "github actions dependencies"
  #---------------------------
  # Flutter Packages
  #---------------------------
  - package-ecosystem: "pub"
    directory: "/pub/helpers"
    schedule:
      interval: "daily"
      # day: "sunday"
      time: "06:00"
    target-branch: "develop"
    labels:
      - "pub dependencies"
