---
version: 2
updates:
  #---------------------------
  # Github Actions
  #---------------------------
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Africa/Johannesburg"
    target-branch: "develop"
    labels:
      - "github actions dependencies"
  #---------------------------
  # Flutter Packages
  #---------------------------
  - package-ecosystem: "pub"
    directory: "/pub/helpers"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Africa/Johannesburg"
    target-branch: "develop"
    labels:
      - "pub dependencies"
  #---------------------------
  # Core
  #---------------------------
  - package-ecosystem: "pub"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Africa/Johannesburg"
    target-branch: "develop"
    labels:
      - "pub dependencies"
  #---------------------------
  # Models
  #---------------------------
  - package-ecosystem: "pub"
    directory: "/packages/models"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Africa/Johannesburg"
    target-branch: "develop"
    labels:
      - "pub dependencies"
