# This file contains the config that is used by the Github Workflows.

# This can be used to control which platforms are build, release, and deployed.
# It is preferable to set all values to 'true'.
build:
  web_build_flag: true
  android_build_flag: true
  windows_build_flag: false

# This can be used to determine the state of releases to Github.
release:
  body: "Release notes here"
  draft: true
  prerelease: true
  generateReleaseNotes: true

# This can be used to manually control whether the app is deployed using the workflows.
deploy:
  uat: true
  production: false

android_deploy:
  android_package_name: "co.za.zanderkotze.multichoice"
  android_track: "alpha"
  android_release_name: "v1.0.0"
  android_deploy_status: "draft"
