name: multichoice

packages:
  - packages/**
  - packages_external/**
  - apps/**

ignore:
  - apps/showcase

scripts:
  analyze:
    run: dart analyze .
    exec:
      failFast: true
      concurrency: 1
      orderDependents: true

  build:
    run: dart run build_runner build --delete-conflicting-outputs
    exec:
      failFast: true
      concurrency: 1
      orderDependents: true

  get:
    run: flutter pub get
    exec:
      failFast: true
      concurrency: 1
      orderDependents: true

  clean-build:
    run: flutter clean && flutter pub get && dart run build_runner build --delete-conflicting-outputs
    exec:
      failFast: true
      concurrency: 1
      orderDependents: true

  upgrade:
    run: flutter pub upgrade --major-versions
    exec:
      failFast: true
      concurrency: 1

  upgrade:global:
    run: flutter clean && flutter pub upgrade --major-versions
    exec:
      failFast: true
      concurrency: 1

  test:all:
    description: |
      Run all tests available.
    run: |
      melos run test:core --no-select && melos run test:multichoice --no-select

  test:core:
    run: flutter test -j 1
    exec:
      failFast: false
      concurrency: 1
      orderDependents: true
    packageFilters:
      flutter: true
      scope: ["core"]

  test:multichoice:
    run: flutter test -j 1
    exec:
      failFast: false
      concurrency: 1
      orderDependents: true
    packageFilters:
      flutter: true
      scope: ["multichoice"]

  test:integration:
    run: flutter test -j 1 --coverage
    exec:
      failFast: false
      concurrency: 1
      orderDependents: true
    packageFilters:
      flutter: true
      scope: ["integration"]

  coverage:all:
    description: |
      Run all tests and generate coverage reports.
    run: |
      melos run coverage:core --no-select && melos run coverage:multichoice --no-select

  coverage:integration:
    run: flutter test -j 1 --coverage
    exec:
      failFast: true
      concurrency: 1
      orderDependents: true
    packageFilters:
      flutter: true
      scope: ["integration"]

  coverage:core:
    run: flutter test -j 1 --coverage
    exec:
      failFast: true
      concurrency: 1
      orderDependents: true
    packageFilters:
      flutter: true
      scope: ["core"]

  coverage:multichoice:
    run: flutter test -j 1 --coverage
    exec:
      failFast: true
      concurrency: 1
      orderDependents: true
    packageFilters:
      flutter: true
      scope: ["multichoice"]

  coverage:multichoice:windows:
    run: flutter test -j 1 --coverage && perl "C:\\ProgramData\\chocolatey\\lib\\lcov\\tools\\bin\\genhtml" --no-function-coverage -o coverage\html coverage\lcov.info && start coverage\html\index.html
    exec:
      failFast: false
      concurrency: 1
      orderDependents: true
    packageFilters:
      flutter: true
      scope: ["multichoice"]

  coverage:core:windows:
    run: flutter test -j 1 --coverage && perl "C:\\ProgramData\\chocolatey\\lib\\lcov\\tools\\bin\\genhtml" --no-function-coverage -o coverage\html coverage\lcov.info && start coverage\html\index.html
    exec:
      failFast: true
      concurrency: 1
      orderDependents: true
    packageFilters:
      scope: "core"

command:
  bootstrap:
    runPubGetInParallel: false
