name: multichoice

packages:
  - packages/**
  - packages_external/**
  - apps/**

ignore:
  - apps/showcase

scripts:
  analyze:
    run: dart analyze .
    exec:
      failFast: true
      concurrency: 1
      orderDependents: true

  build:
    run: dart run build_runner build --delete-conflicting-outputs
    exec:
      failFast: true
      concurrency: 1
      orderDependents: true

  get:
    run: flutter pub get
    exec:
      failFast: true
      concurrency: 1
      orderDependents: true

  clean-build:
    run: flutter clean && flutter pub get && dart run build_runner build --delete-conflicting-outputs
    exec:
      failFast: true
      concurrency: 1
      orderDependents: true

  upgrade:
    run: flutter pub upgrade --major-versions
    exec:
      failFast: true
      concurrency: 1

  upgrade:global:
    run: flutter clean && flutter pub upgrade --major-versions
    exec:
      failFast: true
      concurrency: 1

  test:all:
    description: |
      Run all tests available.
    run: |
      melos run test:core --no-select && melos run test:multichoice --no-select
  # format_coverage --lcov --in coverage/lcov.info -b coverage/html
  test:core:
    run: flutter test -j 1 --coverage && reportgenerator.exe -reports:coverage/lcov.info -targetdir:coverage/html

    exec:
      failFast: false
      concurrency: 1
      orderDependents: true
    packageFilters:
      flutter: true
      scope: ["core"]

  test:multichoice:
    run: flutter test -j 1 --coverage && reportgenerator.exe -reports:coverage/lcov.info -targetdir:coverage/html

    exec:
      failFast: false
      concurrency: 1
      orderDependents: true
    packageFilters:
      flutter: true
      scope: ["multichoice"]

  test:integration:
    run: flutter test -j 1 --coverage && reportgenerator.exe -reports:coverage/lcov.info -targetdir:coverage/html

    exec:
      failFast: false
      concurrency: 1
      orderDependents: true
    packageFilters:
      flutter: true
      scope: ["integration"]

  coverage:core:
    run: flutter test -j 1 --coverage
    packageFilters:
      scope: "core"
    exec:
      concurrency: 1

command:
  bootstrap:
    runPubGetInParallel: false
