name: Build Web
description: "Builds a web version of the app"
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Flutter and Java
      uses: ./.github/workflows/setup-java-flutter

    - name: Start Web Release Build
      shell: bash
      run: flutter build web --base-href='/multichoice/' --release

    # - name: Check if Artifact Already Exists
    #   id: check-artifact
    #   shell: bash
    #   # run: echo "::set-output name=artifact_exists::$(if [ -e web-release ]; then echo true; else echo false; fi)"
    #   run: echo "ARTIFACT_EXISTS=$(if [ -e web-release.zip ]; then echo true; else echo false; fi)" >> $GITHUB_ENV

    - name: Upload Web Build Files
      # if: env.ARTIFACT_EXISTS == false
      uses: actions/upload-artifact@v4
      with:
        name: web-release
        path: ./build/web
        overwrite: true
