part of '../app_theme.dart';

final _darkColors = AppColorsExtension(
  primary: _AppPalette.primary5,
  primaryLight: _AppPalette.geyserLightTone1.withValues(alpha: 0.2),
  secondary: _AppPalette.primary10,
  secondaryLight: _AppPalette.slateGrayLight,
  ternary: _AppPalette.sanJuanTone2,
  foreground: _AppPalette.primary15,
  background: _AppPalette.primary0,
  white: _AppPalette.white,
  black: _AppPalette.black,
  error: _AppPalette.imperialRed,
  success: _AppPalette.pistachio,
  enabled: _AppPalette.enabledColor,
  disabled: _AppPalette.disabledColor,
  filledButtonBackground: _AppPalette.primary5,
  filledButtonForeground: _AppPalette.primary10,
  outlinedButtonForeground: _AppPalette.white,
  outlinedButtonBorder: _AppPalette.white,
  textButtonForeground: _AppPalette.sanJuanTone2,
  textButtonBackground: _AppPalette.geyserLightTone1,
  scaffoldBackground: _AppPalette.primary0,
  cardBackground: _AppPalette.primary15,
  modalBackground: _AppPalette.primary15,
  appBarBackground: _AppPalette.primary15,
  textPrimary: _AppPalette.sanJuanTone2,
  textSecondary: _AppPalette.primary10,
  textTertiary: _AppPalette.slateGrayLight,
  iconColor: _AppPalette.sanJuanTone2,
  linkColor: _AppPalette.primary10,
  accent: _AppPalette.geyserTone2,
);
