part of '../app_theme.dart';

final _lightColors = AppColorsExtension(
  primary: _AppPalette.geyserTone1,
  primaryLight: _AppPalette.geyserLightTone1,
  secondary: _AppPalette.sanJuanTone1,
  secondaryLight: _AppPalette.sanJuanLightTone1,
  ternary: _AppPalette.bigStoneTone1,
  foreground: _AppPalette.bigStoneTone1,
  background: _AppPalette.slateGrayTone1,
  white: null,
  black: _AppPalette.black,
  error: _AppPalette.imperialRed,
  success: _AppPalette.darkSpringGreen,
  enabled: _AppPalette.enabledColor,
  disabled: _AppPalette.disabledColor,
  filledButtonBackground: _AppPalette.geyserTone1,
  filledButtonForeground: _AppPalette.sanJuanTone1,
  outlinedButtonForeground: _AppPalette.geyserTone1,
  outlinedButtonBorder: _AppPalette.geyserTone1,
  textButtonForeground: _AppPalette.black,
  textButtonBackground: _AppPalette.geyserLightTone1,
  scaffoldBackground: _AppPalette.slateGrayTone1,
  cardBackground: _AppPalette.sanJuanTone1,
  modalBackground: _AppPalette.sanJuanTone1,
  appBarBackground: _AppPalette.bigStoneTone1,
  textPrimary: _AppPalette.bigStoneTone1,
  textSecondary: _AppPalette.geyserTone1,
  textTertiary: _AppPalette.geyserLightTone1,
  iconColor: _AppPalette.geyserTone1,
  linkColor: _AppPalette.sanJuanTone1,
  accent: _AppPalette.sanJuanTone1,
);
