// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyA3_VXMz5bCPhDzQ4psfOHl5mEZt8s_w-4',
//     appId: '1:82796040762:web:15fecbf2203c038ee4db03',
//     messagingSenderId: '82796040762',
//     projectId: 'multichoice-412309',
//     authDomain: 'multichoice-412309.firebaseapp.com',
//     storageBucket: 'multichoice-412309.appspot.com',
//     measurementId: 'G-RKRDGDJMDK',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyA9oQ4EKnvNdGnh_cVRoTcQ62tNij9YNSY',
//     appId: '1:82796040762:android:7d86369ea3e82786e4db03',
//     messagingSenderId: '82796040762',
//     projectId: 'multichoice-412309',
//     storageBucket: 'multichoice-412309.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCbM12acc3yLQbmEHxxqMij_EVJB9FJN8E',
//     appId: '1:82796040762:ios:60f8a21e5479962fe4db03',
//     messagingSenderId: '82796040762',
//     projectId: 'multichoice-412309',
//     storageBucket: 'multichoice-412309.appspot.com',
//     iosBundleId: 'co.za.zanderkotze.multichoice',
//   );
// }
