# .devcontainer/Dockerfile
# FROM mobiledevops/flutter-sdk-image:latest
FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04

# Set the default shell for the integrated terminal
SHELL ["/bin/bash", "-c"]

# Install additional dependencies if needed

