# Stage 1: Android SDK
FROM google/cloud-sdk:latest as android_stage

# FROM eclipse-temurin

# Set Android environment variables
ENV ANDROID_HOME=/opt/android-sdk

# Install dependencies
USER root
RUN apt-get update && \
    apt-get install -y \
    git \
    unzip \
    curl \
    wget

# Install Android SDK
USER root
RUN mkdir -p $ANDROID_HOME/cmdline-tools && \
    wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip -O /tmp/android-sdk.zip && \
    unzip /tmp/android-sdk.zip -d $ANDROID_HOME/cmdline-tools && \
    rm /tmp/android-sdk.zip

# Add Android SDK tools to PATH
ENV PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/cmdline-tools/tools/bin:$ANDROID_HOME/platform-tools:$PATH

# Accept Android SDK licenses
# RUN yes | sdkmanager --licenses

# Switch back to non-root user for the Flutter stage
USER flutteruser
WORKDIR /home/flutteruser

# Stage 2: Flutter
FROM ubuntu:20.04 as flutter_stage

# Set Flutter environment variables
ENV FLUTTER_HOME=/opt/flutter
ENV PATH=$FLUTTER_HOME/bin:$PATH

# Install dependencies
USER root
RUN apt-get update && \
    apt-get install -y \
    git \
    unzip \
    curl \
    wget

# Create a non-root user for Flutter
RUN useradd -ms /bin/bash flutteruser
USER flutteruser
WORKDIR /home/flutteruser

# Create the Flutter directory with the correct permissions
USER root
RUN mkdir -p $FLUTTER_HOME
# RUN chown -R flutteruser:flutteruser $FLUTTER_HOME

# Manually install Flutter in the desired location
RUN git clone https://github.com/flutter/flutter.git -b stable --depth 1 $FLUTTER_HOME

# Run "flutter doctor" to ensure Flutter setup
RUN $FLUTTER_HOME/bin/flutter doctor

RUN flutter precache

RUN chown -R flutteruser:flutteruser $FLUTTER_HOME
RUN chown -R flutteruser:flutteruser /opt/flutter/bin/cache

# Stage 3: Final image
FROM ubuntu:20.04

# Set environment variables
ENV ANDROID_HOME=/opt/android-sdk
ENV FLUTTER_HOME=/opt/flutter
ENV FLUTTER_HOME_NEW=/usr/local/flutter
ENV PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/cmdline-tools/tools/bin:$ANDROID_HOME/platform-tools:$FLUTTER_HOME/bin:$PATH

# Install dependencies
USER root
RUN apt-get update && \
    apt-get install -y \
    git \
    unzip \
    curl

# Create a non-root user for the final image
RUN useradd -ms /bin/bash flutteruser
USER flutteruser
WORKDIR /home/flutteruser

# Copy Android SDK from the Android SDK stage
COPY --from=android_stage $ANDROID_HOME $ANDROID_HOME

# Copy Flutter from the Flutter stage
COPY --from=flutter_stage $FLUTTER_HOME $FLUTTER_HOME

# Install any additional dependencies needed for Flutter development
# ...

# Set up your working directory for the Flutter app
WORKDIR /home/flutteruser/app

# Clone your Flutter app repository
# RUN git clone <your_flutter_app_git_repository> .

# Install Flutter dependencies
# RUN chown -R flutteruser:flutteruser /opt/flutter/bin/cache
# RUN git config --global --add safe.directory /opt/flutter
USER flutteruser
# RUN flutter pub get

# Expose the default Flutter port for debugging
EXPOSE 3000

# Command to run your Flutter application
# CMD ["flutter", "run", "--release"]
