part of '../app_theme.dart';

final _darkAppColors = AppColorsExtension(
  primary: AppPalette.primary5,
  primaryLight: AppPalette.geyserLightTone1.withValues(alpha: 0.2),
  secondary: AppPalette.primary10,
  secondaryLight: AppPalette.slateGrayLight,
  ternary: AppPalette.sanJuanTone2,
  foreground: AppPalette.primary15,
  background: AppPalette.primary0,
  white: AppPalette.white,
  black: AppPalette.black,
  error: null,
  success: null,
  enabled: AppPalette.enabledColor,
  disabled: AppPalette.disabledColor,
  filledButtonBackground: AppPalette.primary5,
  filledButtonForeground: AppPalette.primary10,
  outlinedButtonForeground: AppPalette.white,
  outlinedButtonBorder: AppPalette.white,
  textButtonForeground: AppPalette.sanJuanTone2,
  textButtonBackground: AppPalette.geyserLightTone1,
  scaffoldBackground: AppPalette.primary0,
  cardBackground: AppPalette.primary15,
  modalBackground: AppPalette.primary15,
  appBarBackground: AppPalette.primary15,
  textPrimary: AppPalette.sanJuanTone2,
  textSecondary: AppPalette.primary10,
  textTertiary: AppPalette.slateGrayLight,
  iconColor: AppPalette.sanJuanTone2,
  linkColor: AppPalette.primary10,
  accent: AppPalette.primary10,
);
