part of '../app_theme.dart';

final _lightAppColors = AppColorsExtension(
  primary: AppPalette.geyserTone1,
  primaryLight: AppPalette.geyserLightTone1,
  secondary: AppPalette.sanJuanTone1,
  secondaryLight: AppPalette.sanJuanLightTone1,
  ternary: AppPalette.bigStoneTone1,
  foreground: AppPalette.bigStoneTone1,
  background: AppPalette.slateGrayTone1,
  white: null,
  black: AppPalette.black,
  error: AppPalette.imperialRed,
  success: AppPalette.darkSpringGreen,
  enabled: AppPalette.enabledColor,
  disabled: AppPalette.disabledColor,
  filledButtonBackground: AppPalette.geyserTone1,
  filledButtonForeground: AppPalette.sanJuanTone1,
  outlinedButtonForeground: AppPalette.geyserTone1,
  outlinedButtonBorder: AppPalette.geyserTone1,
  textButtonForeground: AppPalette.black,
  textButtonBackground: AppPalette.geyserLightTone1,
  scaffoldBackground: AppPalette.slateGrayTone1,
  cardBackground: AppPalette.sanJuanTone1,
  modalBackground: AppPalette.sanJuanTone1,
  appBarBackground: AppPalette.bigStoneTone1,
  textPrimary: AppPalette.bigStoneTone1,
  textSecondary: AppPalette.geyserTone1,
  textTertiary: AppPalette.geyserLightTone1,
  iconColor: AppPalette.geyserTone1,
  linkColor: AppPalette.sanJuanTone1,
  accent: AppPalette.sanJuanTone1,
);
