include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    one_member_abstracts: ignore

analyzer:
  exclude:
    - lib/generated/**
    - lib/**.g.dart
    - lib/**.freezed.dart
  errors:
    invalid_annotation_target: ignore
