// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, document_ignores, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;
import 'package:multichoice/config/app_config.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are only configured for Android and web.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: AppConfig.webApiKey,
    appId: AppConfig.webAppId,
    messagingSenderId: AppConfig.messagingSenderId,
    projectId: AppConfig.firebaseProjectId,
    authDomain: AppConfig.authDomain,
    storageBucket: AppConfig.storageBucket,
    measurementId: AppConfig.webMeasurementId,
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: AppConfig.androidApiKey,
    appId: AppConfig.androidAppId,
    messagingSenderId: AppConfig.messagingSenderId,
    projectId: AppConfig.firebaseProjectId,
    storageBucket: AppConfig.storageBucket,
  );
}
