name: Common Setup
description: "Sets up Java and Flutter for reusability"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.16.x"
        channel: "stable"
        cache: true

    - name: Get dependencies
      shell: bash
      run: flutter pub get

    - name: Dart Build-runner
      shell: bash
      run: dart run build_runner build --delete-conflicting-outputs
