name: "Tokenized Commit"
description: "Commits and pushes changes with a GitHub App token"

inputs:
  github_token:
    description: "GitHub token for authentication"
    required: true
  repository:
    description: "Repository name in the format 'owner/repo'"
    required: true
    default: "${{ github.repository }}"
  file_path:
    description: "Path to the pubspec.yaml file"
    required: true
    default: "apps/multichoice/pubspec.yaml"
  commit_message:
    description: "Commit message for the changes"
    required: true
    default: "Bump to $new_version [skip ci]"
  branch_name:
    description: "Branch name to push changes to"
    required: true
    default: "tmp-main"

runs:
  using: "composite"
  steps:
    # - name: Checkout Branch
    #   uses: actions/checkout@v4
    #   with:
    #     ref: ${{ inputs.branch_name }}
    #     fetch-depth: 0
    #     token: ${{ inputs.github_token }}

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "VersionBumpingBot"
        git config --global user.email "bot@versionbumpingbot.com"

    - name: Commit Changes
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        REPO: ${{ inputs.repo }}
      run: |
        git add ${{ inputs.pubspec_path }}
        git commit -m "${{ inputs.commit_message }}" || {
          echo "::error::Failed to commit changes"
          exit 1
        }
        echo "Git status: $(git status)"

    - name: Push Changes
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        REPO: ${{ inputs.repository }}
      run: |
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${REPO}.git
        git push origin HEAD:${{ inputs.branch_name }} || {
          echo "::error::Failed to push version bump to ${{ inputs.branch_name }}"
          exit 1
        }
