name: Web Build workflow
on:
  workflow_call:
    inputs:
      pubspec_filename:
        required: true
        type: string
      environment_flag:
        required: true
        type: string
      build_flag:
        required: true
        type: boolean

jobs:
  buildWeb:
    name: Web - Test, Analyze, Build
    if: ${{ inputs.build_flag == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: ./.github/actions/setup-flutter

      - name: Start Web Release Build
        run: flutter build web --base-href='/multichoice/' --${{ inputs.environment_flag }}
        working-directory: apps/multichoice/

      - name: Upload Web Build Files
        uses: actions/upload-artifact@v4
        with:
          name: web-release
          path: .apps/multichoice/build/web
