name: Build Android, Web, & Windows Apps
on:
  # push:
  #   branches:
  #     - "main"
  #     - "develop"
  # pull_request:
  #   branches:
  #     - "main"
  #     - "develop"
  workflow_call:
    inputs:
      web-build-flag:
        required: true
        type: boolean
      web-environment-flag:
        required: true
        type: string
      android-build-flag:
        required: true
        type: boolean
      android-environment-flag:
        required: true
        type: string
      android-versionNumber:
        required: true
        type: string
      windows-build-flag:
        required: true
        type: boolean
      windows-environment-flag:
        required: true
        type: string

  workflow_dispatch:

jobs:
  buildWeb:
    name: "Build Web app"
    uses: ./.github/workflows/_build-web-app.yml
    with:
      environment-flag: ${{ inputs.web-environment-flag }}
      build-flag: ${{ inputs.web-build-flag }}
  buildAndroid:
    name: "Build Android app"
    uses: ./.github/workflows/_build-android-app.yml
    secrets: inherit
    with:
      environment-flag: ${{ inputs.android-environment-flag }}
      versionNumber: ${{ inputs.android-versionNumber }}
  buildWindows:
    name: "Build Windows app"
    uses: ./.github/workflows/_build-windows-app.yml
    with:
      environment-flag: ${{ inputs.windows-environment-flag }}
