name: Build Android, Web, & Windows Apps
on:
  workflow_call:
    inputs:
      pubspec_filename:
        required: true
        type: string
      web_build_flag:
        required: true
        type: boolean
      web_environment_flag:
        required: true
        type: string
      android_build_flag:
        required: true
        type: boolean
      android_environment_flag:
        required: true
        type: string
      android_versionNumber:
        required: true
        type: string
      android_build_artifact:
        required: true
        type: string
      android_build_appbundle:
        required: true
        type: boolean
      windows_build_flag:
        required: true
        type: boolean
      windows_environment_flag:
        required: true
        type: string

jobs:
  buildWeb:
    name: Web
    uses: ./.github/workflows/_build-web-app.yml
    with:
      pubspec_filename: ${{ inputs.pubspec_filename }}
      environment_flag: ${{ inputs.web_environment_flag }}
      build_flag: ${{ inputs.web_build_flag }}
  buildAndroid:
    name: Android
    uses: ./.github/workflows/_build-android-app.yml
    secrets: inherit
    with:
      pubspec_filename: ${{ inputs.pubspec_filename }}
      environment_flag: ${{ inputs.android_environment_flag }}
      versionNumber: ${{ inputs.android_versionNumber }}
      build_flag: ${{ inputs.android_build_flag }}
      build_artifact: ${{ inputs.android_build_artifact }}
      build_appbundle: ${{ inputs.android_build_appbundle }}
  buildWindows:
    name: Windows
    uses: ./.github/workflows/_build-windows-app.yml
    with:
      pubspec_filename: ${{ inputs.pubspec_filename }}
      environment_flag: ${{ inputs.windows_environment_flag }}
      build_flag: ${{ inputs.windows_build_flag }}
