name: Android Build workflow
on:
  workflow_call:
    inputs:
      environment-flag:
        required: true
        type: string
      versionNumber:
        required: true
        type: string
jobs:
  pre-build:
    name: Create missing elements for building apps
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter and Java
        uses: ./.github/actions/setup-java-flutter

      - name: Create version number
        uses: ./.github/actions/android-versioning

  buildAndroid:
    name: Build Android
    needs: pre-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter and Java
        uses: ./.github/actions/setup-java-flutter

      # - name: Set up Java
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: "zulu"
      #     java-version: "17"
      #     cache: gradle

      # - name: Set up Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #     flutter-version: "3.16.x"
      #     channel: "stable"
      #     cache: true

      # - name: Get dependencies
      #   shell: bash
      #   run: flutter pub get

      # - name: Get version.txt
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: gitversion

      # - name: Create new file without newline char from version.txt
      #   run: tr -d '\n' < version.txt > version1.txt

      # - name: Read version
      #   id: version
      #   uses: juliangruber/read-file-action@v1
      #   with:
      #     path: version1.txt

      # - name: Update version in YAML
      #   run: |
      #     # sed -i 's/99.99.99+99/${{ steps.version.outputs.content }}+${{ github.run_number }}/g' pubspec.yaml
      #     sed -Ei "s/^version: (.*)/version: ${{ steps.version.outputs.content }}+${{ github.run_number }}/g" pubspec.yaml

      - name: Get pubspec.yaml
        uses: actions/download-artifact@v4
        with:
          name: pubspec-file

      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Create key.properties
        if: ${{ inputs.environment-flag }} == 'release'
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      - name: Start ${{ inputs.environment-flag }} build
        run: flutter build appbundle --${{ inputs.environment-flag }}

      - name: Upload Android ${{ inputs.environment-flag }}
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: build/app/outputs/bundle/release/app-release.aab
