name: Build Android, Web, & Windows Apps
on:
  # push:
  #   branches:
  #     - "main"
  #     - "develop"
  # pull_request:
  #   branches:
  #     - "main"
  #     - "develop"
  workflow_call:
    inputs:
      web-build-flag:
        required: true
        type: boolean
      web-environment-flag:
        required: true
        type: string
      android-build-flag:
        required: true
        type: boolean
      android-environment-flag:
        required: true
        type: string
      android-versionNumber:
        required: true
        type: string
      windows-build-flag:
        required: true
        type: boolean
      windows-environment-flag:
        required: true
        type: string
    # outputs:
    #   results:
    #     description: "All build results, true or false"
    #     value: ${{ results.outputs.result }}
    #   web-success:
    #     description: "Web build results, true or false"
    #     value: ${{ results.outputs.web }}
    #   android-success:
    #     description: "Android build results, true or false"
    #     value: ${{ results.outputs.android }}
    #   windows-success:
    #     description: "Windows build results, true or false"
    #     value: ${{ results.outputs.windows }}

  # workflow_dispatch:

jobs:
  buildWeb:
    name: "Build Web app"
    uses: ./.github/workflows/_build-web-app.yml
    with:
      environment-flag: ${{ inputs.web-environment-flag }}
      build-flag: ${{ inputs.web-build-flag }}
  buildAndroid:
    name: "Build Android app"
    uses: ./.github/workflows/_build-android-app.yml
    secrets: inherit
    with:
      environment-flag: ${{ inputs.android-environment-flag }}
      versionNumber: ${{ inputs.android-versionNumber }}
      build-flag: ${{ inputs.android-build-flag }}
  buildWindows:
    name: "Build Windows app"
    uses: ./.github/workflows/_build-windows-app.yml
    with:
      environment-flag: ${{ inputs.windows-environment-flag }}
      build-flag: ${{ inputs.windows-build-flag }}

  # results:
  #   name: "Determine build sucess, failure, or skip"
  #   runs-on: ubuntu-latest
  #   outputs:
  #     result: ${{ steps.id-output-result.outputs.result }}
  #     web: ${{ steps.id-web-success.outputs.web }}
  #     android: ${{ steps.id-android-success.outputs.android }}
  #     windows: ${{ steps.id-windows-success.outputs.windows }}

  #   steps:
  #     - name: "Output result"
  #       id: id-output-result
  #       if: jobs.buildWeb.result == 'success' || jobs.buildAndroid.result == 'success' || jobs.buildWindows.result == 'success'
  #       run: echo "result=true" >> "$GITHUB_OUTPUT"

  #     - name: "Create build-results.txt with results"
  #       run: echo ${{ steps.id-output-result.outputs.result }} > build-results.txt

  #     - name: Upload results as artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: build-results
  #         path: build-results.txt

  #     - name: "Run if Web build successfully"
  #       id: id-web-success
  #       if: jobs.buildWeb.result == 'success'
  #       run: echo "web=true" >> "$GITHUB_OUTPUT"

  #     - name: "Run if Android build successfully"
  #       id: id-android-success
  #       if: jobs.buildAndroid.result == 'success'
  #       run: echo "android=true" >> "$GITHUB_OUTPUT"

  #     - name: "Run if Windows build successfully"
  #       id: id-windows-success
  #       if: jobs.buildWindows.result == 'success'
  #       run: echo "windows=true" >> "$GITHUB_OUTPUT"
