name: Web Build workflow
on:
  workflow_call:
    inputs:
      environment-flag:
        required: true
        type: string

jobs:
  buildWeb:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.x"
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Start Web Release Build
        run: flutter build web --base-href='/multichoice/' --${{ inputs.environment-flag }}

      - name: Upload Web Build Files
        uses: actions/upload-artifact@v4
        with:
          name: web-release
          path: ./build/web
