name: Build Android, Web, & Windows Apps
on:
  workflow_call:
    inputs:
      pubspec-filename:
        required: true
        type: string
      web-build-flag:
        required: true
        type: boolean
      web-environment-flag:
        required: true
        type: string
      android-build-flag:
        required: true
        type: boolean
      android-environment-flag:
        required: true
        type: string
      android-versionNumber:
        required: true
        type: string
      android-build-artifact:
        required: true
        type: string
      windows-build-flag:
        required: true
        type: boolean
      windows-environment-flag:
        required: true
        type: string

jobs:
  buildWeb:
    name: "Build Web app"
    uses: ./.github/workflows/_build-web-app.yml
    with:
      pubspec-filename: ${{ inputs.pubspec-filename }}
      environment-flag: ${{ inputs.web-environment-flag }}
      build-flag: ${{ inputs.web-build-flag }}
  buildAndroid:
    name: "Build Android app"
    uses: ./.github/workflows/_build-android-app.yml
    secrets: inherit
    with:
      pubspec-filename: ${{ inputs.pubspec-filename }}
      environment-flag: ${{ inputs.android-environment-flag }}
      versionNumber: ${{ inputs.android-versionNumber }}
      build-flag: ${{ inputs.android-build-flag }}
      build-artifact: ${{ inputs.android-build-artifact }}
  buildWindows:
    name: "Build Windows app"
    uses: ./.github/workflows/_build-windows-app.yml
    with:
      pubspec-filename: ${{ inputs.pubspec-filename }}
      environment-flag: ${{ inputs.windows-environment-flag }}
      build-flag: ${{ inputs.windows-build-flag }}
