name: Windows Build workflow
on:
  workflow_call:
    inputs:
      pubspec_filename:
        required: true
        type: string
      environment_flag:
        required: true
        type: string
      build_flag:
        required: true
        type: boolean

jobs:
  buildWindows:
    name: Windows - Test, Analyze, Build
    if: ${{ inputs.build_flag == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
