name: Android Build workflow
on:
  workflow_call:
    inputs:
      pubspec_filename:
        required: true
        type: string
      environment_flag:
        required: true
        type: string
      versionNumber:
        required: true
        type: string
      build_flag:
        required: true
        type: boolean
      build_artifact:
        required: true
        type: string
      build_appbundle:
        required: true
        type: boolean

jobs:
  testAnalyzeBuildAndroid:
    name: Android - Test, Analyze, Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter and Java
        uses: ./.github/actions/setup-java-flutter

      - name: melos test all
        run: melos test:all

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          fail_ci_if_error: true

      - run: echo "Starting analyze"

      - name: ⚠️ℹ️ Run Dart analysis
        uses: zgosalvez/github-actions-analyze-dart@v3
        with:
          working-directory: "${{github.workspace}}/"

      - run: echo "Starting build process"

      - name: Get pubspec.yaml
        if: ${{ inputs.build_flag == true }} && success()
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.pubspec_filename }}
          path: ${{ github.workspace }}/apps/multichoice/

      - name: Download Android keystore
        id: android_keystore
        if: success()
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Create key.properties
        if: ${{ inputs.environment_flag }} == 'release'
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> key.properties
        working-directory: apps/multichoice/android/

      - name: Create secrets.dart
        run: |
          mkdir auth
          echo "String webApiKey = '${{ secrets.WEB_API_KEY }}';" > auth/secrets.dart
          echo "String webAppId = '${{ secrets.WEB_APP_ID }}';" >> auth/secrets.dart
          echo "String androidApiKey = '${{ secrets.ANDROID_API_KEY }}';" >> auth/secrets.dart
          echo "String androidAppId = '${{ secrets.ANDROID_APP_ID }}';" >> auth/secrets.dart
          echo "String iosApiKey = '${{ secrets.IOS_API_KEY }}';" >> auth/secrets.dart
          echo "String iosAppId = '${{ secrets.IOS_APP_ID }}';" >> auth/secrets.dart
        working-directory: apps/multichoice/lib/

      - name: Start appbundle ${{ inputs.environment_flag }} build
        if: ${{ inputs.build_appbundle == true }} && success()
        run: flutter build appbundle --${{ inputs.environment_flag }}
        working-directory: apps/multichoice/

      - name: Start apk ${{ inputs.environment_flag }} build
        if: success()
        run: flutter build apk --${{ inputs.environment_flag }}
        working-directory: apps/multichoice/

      - name: Upload Android ${{ inputs.environment_flag }} appbundle
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.build_artifact }}
          path: ./apps/multichoice/build/app/outputs/bundle/${{ inputs.environment_flag }}/app-${{ inputs.environment_flag }}.aab

      - name: Upload artifact to Firebase App Distribution
        if: success()
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: testers
          file: ./apps/multichoice/build/app/outputs/flutter-apk/app-${{ inputs.environment_flag }}.apk
          releaseNotesFile: ./apps/multichoice/CHANGELOG.txt
          debug: true
