name: Deploy Android, Web, & Windows Apps
on:
  workflow_call:
    inputs:
      web_deploy_flag:
        required: true
        type: boolean
      web_environment_flag:
        required: true
        type: string

      android_deploy_flag:
        required: true
        type: boolean
      android_environment_flag:
        required: true
        type: string
      android_package_name:
        required: true
        type: string
      android_environment_url:
        required: true
        type: string
      android_track:
        required: true
        type: string
      android_release_name:
        required: true
        type: string
      android_deploy_status:
        required: true
        type: string

      windows_deploy_flag:
        required: true
        type: boolean
      windows_environment_flag:
        required: true
        type: string

  workflow_dispatch:

jobs:
  deployWeb:
    name: "Deploy Web app"
    uses: ./.github/workflows/_deploy-web-app.yml
    permissions:
      contents: write
    secrets: inherit
    with:
      deploy_flag: ${{ inputs.web_deploy_flag }}
      environment_flag: ${{ inputs.web_environment_flag }}
  deployAndroid:
    name: "Deploy Android app"
    uses: ./.github/workflows/_deploy-android-app.yml
    secrets: inherit
    with:
      deploy_flag: ${{ inputs.android_deploy_flag }}
      environment_flag: ${{ inputs.android_environment_flag }}
      package_name: ${{ inputs.android_package_name }}
      track: ${{ inputs.android_track }}
      release_name: ${{ inputs.android_release_name }}
      deploy_status: ${{ inputs.android_deploy_status }}
  deployWindows:
    name: "Deploy Windows app"
    uses: ./.github/workflows/_deploy-windows-app.yml
    with:
      deploy_flag: ${{ inputs.windows_deploy_flag }}
      environment_flag: ${{ inputs.windows_environment_flag }}
