name: 📦🚀 Deploy Web app for an environment

on:
  workflow_call:
    inputs:
      environment-flag:
        required: true
        type: string
  workflow_dispatch:

jobs:
  deployWeb:
    name: Deploy Web Build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Web Release
        uses: actions/download-artifact@v4
        with:
          name: web-release

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
