name: 📦🚀 Deploy Web app for an environment

on:
  workflow_call:
    inputs:
      deploy_flag:
        required: true
        type: boolean
      environment-flag:
        required: true
        type: string
  workflow_dispatch:

jobs:
  deployWeb:
    name: Deploy Web Build
    if: ${{ inputs.deploy_flag == true }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: release_workflow.yml
          workflow_conclusion: success
          search_artifacts: true
          name: web-release

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
