name: Semantic Versioning & Build Increment

on:
  pull_request:
    types: [closed]
    branches: [develop]

jobs:
  version-bump:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version based on PR labels
        uses: ./.github/actions/version-bump
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: "apps/multichoice/pubspec.yaml"
