name: Linting and Analysis

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - "**"
  workflow_dispatch:

concurrency:
  group: linting-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter-with-java
        with:
          setup_java: "false"

      - name: Run Melos Analyze
        run: melos analyze
        shell: bash

      ##############################################
      # Run test coverage and upload to Codecov
      ##############################################
      - name: Run Melos Coverage
        run: melos coverage:all

      - name: Merge Coverage Reports
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p coverage
          cat apps/multichoice/coverage/lcov.info packages/core/coverage/lcov.info > coverage/lcov.info

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          fail_ci_if_error: true
