name: Common Setup

on:
  workflow_call:

jobs:
  setup:
    # name: Set up Java and Flutter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter and Java
        uses: ./.github/workflows/setup-java-flutter

      # - name: Checkout repository
      #   uses: actions/checkout@v4

      # - name: Set up Java
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: "zulu"
      #     java-version: "17"
      #     cache: gradle

      # - name: Set up Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #     flutter-version: "3.16.x"
      #     channel: "stable"
      #     cache: true

      # - name: Get dependencies
      #   shell: bash
      #   run: flutter pub get

      # # Add any other common setup steps here
