name: Common Setup

on:
  # workflow_call:
  # push:
  #   branches:
  #     - fix-workflows
  workflow_dispatch:

jobs:
  setup:
    name: Set up Java and Flutter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: read-config-file
        uses: pietrobolcato/action-read-yaml@1.1.0
        id: read_config_yaml
        with:
          config: ${{ github.workspace }}/config.yml

      - id: echo_config
        run: |
          echo "draft: ${{ steps.read_config_yaml.outputs['release.draft'] }}"
          echo "prerelease: ${{ steps.read_config_yaml.outputs['release.prerelease'] }}"

      # - id: read_config
      #   uses: actions/github-script@v7
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       const yaml = require('js-yaml');
      #       const fs = require('fs');
      #       const path = require('path');

      #       const configFile = path.join(process.env.GITHUB_WORKSPACE, 'config.yml');
      #       const config = yaml.load(fs.readFileSync(configFile, 'utf8'));

      #       console.log(JSON.stringify(config));
      #       const draft = process.env.CONFIG_RELEASE_DRAFT = config.release.draft ? 'true' : 'false';
      #       const prerelease = process.env.CONFIG_RELEASE_PRERELEASE = config.release.prerelease ? 'true' : 'false';

      #       console.log("${CONFIG_RELEASE_DRAFT}, ${CONFIG_RELEASE_PRERELEASE}");

      #       return draft.concat(':', prerelease)

      #     result-encoding: string
