name: Web Release

on:
  push:
    branches: ["main"]

  # pull_request:
  #   branches: ["main", "develop"]

  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  # build:
  #   name: Create Web Build
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Build Web
  #       uses: ./.github/workflows/build-web
  build:
    name: Create Web Build
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter and Java
        uses: ./.github/workflows/setup-java-flutter

      - name: Start Web Release Build
        run: flutter build web --base-href='/multichoice/' --release

      - name: Upload Web Build Files
        uses: actions/upload-artifact@v4
        with:
          name: web-release
          path: ./build/web

  deploy:
    name: Deploy Web Build
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Web Release
        uses: actions/download-artifact@v4
        with:
          name: web-release

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
