import 'package:multichoice/i18n/strings.g.dart';

enum TooltipEnums {
  back,
  newTab,
  newEntry,
  search,
  tabOptions,
  ok,
  cancel,
  close,
  lightDarkMode,
  deleteAllData,
  deleteTab,
  deleteEntry,
  editTab,
  editEntry,
  importExport,
  import,
  export,
  settings,
  home,
  editOrder;

  String label(Translations t) => switch (this) {
    TooltipEnums.back => t.tooltips.back,
    TooltipEnums.newTab => t.tooltips.newTab,
    TooltipEnums.newEntry => t.tooltips.newEntry,
    TooltipEnums.search => t.tooltips.search,
    TooltipEnums.tabOptions => t.tooltips.tabOptions,
    TooltipEnums.ok => t.tooltips.ok,
    TooltipEnums.cancel => t.tooltips.cancel,
    TooltipEnums.close => t.tooltips.close,
    TooltipEnums.lightDarkMode => t.tooltips.lightDarkMode,
    TooltipEnums.deleteAllData => t.tooltips.deleteAllData,
    TooltipEnums.deleteTab => t.tooltips.deleteTab,
    TooltipEnums.deleteEntry => t.tooltips.deleteEntry,
    TooltipEnums.editTab => t.tooltips.editTab,
    TooltipEnums.editEntry => t.tooltips.editEntry,
    TooltipEnums.importExport => t.tooltips.importExport,
    TooltipEnums.import => t.tooltips.import,
    TooltipEnums.export => t.tooltips.export,
    TooltipEnums.settings => t.tooltips.settings,
    TooltipEnums.home => t.tooltips.home,
    TooltipEnums.editOrder => t.tooltips.editOrder,
  };
}
